# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

# レスポンスJSONを制御する
gem 'active_model_serializers'

# railsの起動時間を短縮する（標準gem）
gem 'bootsnap', require: false

# 環境毎の設定管理を行う
gem 'config'

# ユーザー認証を提供する
gem 'devise'

# devise を日本語化する
gem 'devise-i18n'

# ユーザーのトークン認証を提供する
gem 'devise_token_auth'

gem 'nokogiri', '~> 1.18'

# ページネーション機能を提供する
gem 'kaminari'

# MySQLに接続する
gem 'mysql2', '~> 0.5'

# pumaサーバーを使えるようにする（標準gem）
# gem "puma", "~> 5.0"
# Gemfile
gem 'puma', '~> 6.6'

# cors設定を管理する
gem 'rack-cors'

# rails本体（標準gem）
gem 'rails', '~> 7.1.5'

# メッセージを日本語化
gem 'rails-i18n'

# enumを日本語化する
gem 'enum_help'

# タイムゾーン情報を提供する（標準gem）
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  # N+1発生時にアラートを表示する
  gem 'bullet'
  # テスト用データを作成する
  gem 'factory_bot_rails'
  gem 'faker'
  # 開発環境でメール送信をテストする
  gem 'letter_opener_web'
  # pryコンソールを使えるようにする
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  # テストフレームワーク　rspecを導入する
  gem 'rspec-rails'
  # rubocop を使えるようにする。
  gem 'rubocop-faker'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
end
